/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package implementeringform;

import java.awt.Graphics;// Importerar Graphics-klassen som används för att rita former
import java.util.ArrayList;// Importerar ArrayList som används för att lagra flera objekt i en lista

/**
 *
 * @author taglu01
 */
public class Form1JPanel extends javax.swing.JPanel implements Runnable{

    public ArrayList<Form> former = new ArrayList<>();// Lista som lagrar alla former som ritas i programmet
    FileManager fmgr = new FileManager();// Objekt som hanterar läsning och skrivning av filer
    Thread trad;// Tråd som används för att köra programlogik i bakgrunden
    boolean running = false;// Variabel som visar om programmet/tråden körs eller inte
    /**
     * Creates new form Form1JPanel
     */
    public Form1JPanel(){
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jbtnRensa = new javax.swing.JButton();
        jbtnSpara = new javax.swing.JButton();
        RbtnCirkel = new javax.swing.JRadioButton();
        RbtnTriangel = new javax.swing.JRadioButton();
        RbtnRektangel = new javax.swing.JRadioButton();
        jbtnHämta = new javax.swing.JButton();
        tJbtnStarta = new javax.swing.JToggleButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jbtnRensa.setText("Rensa");
        jbtnRensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRensaActionPerformed(evt);
            }
        });

        jbtnSpara.setText("Spara");
        jbtnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSparaActionPerformed(evt);
            }
        });

        buttonGroup1.add(RbtnCirkel);
        RbtnCirkel.setSelected(true);
        RbtnCirkel.setText("Cirkel");

        buttonGroup1.add(RbtnTriangel);
        RbtnTriangel.setText("Triangel");

        buttonGroup1.add(RbtnRektangel);
        RbtnRektangel.setText("Rektangel");

        jbtnHämta.setText("Hämta");
        jbtnHämta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHämtaActionPerformed(evt);
            }
        });

        tJbtnStarta.setText("Starta");
        tJbtnStarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJbtnStartaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RbtnCirkel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbtnTriangel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbtnRektangel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jbtnSpara)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tJbtnStarta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnRensa)
                    .addComponent(jbtnHämta))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSpara)
                    .addComponent(RbtnCirkel)
                    .addComponent(RbtnTriangel)
                    .addComponent(RbtnRektangel)
                    .addComponent(jbtnHämta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRensa)
                    .addComponent(tJbtnStarta))
                .addContainerGap(232, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSparaActionPerformed
        fmgr.saveToFile(former);// Sparar alla former i listan till en fil
    }//GEN-LAST:event_jbtnSparaActionPerformed

    private void jbtnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRensaActionPerformed
    this.former.clear();// Tar bort alla former från listan
    
    repaint();// Ritar om panelen så att ändringarna visas på skärmen
    }//GEN-LAST:event_jbtnRensaActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    // Hämtar musens X- och Y-koordinater där användaren klickade
    int x = evt.getX();
    int y = evt.getY();
    
    int b = (int) (Math.random() * 301) +5;// Slumpar bredd mellan 5 och 305
    int h = (int) (Math.random() * 50) +5;// Slumpar höjd mellan 5 och 55
    
    if(this.RbtnTriangel.isSelected()){// Om radioknappen för triangel är vald
        Form t = new Triangel (x, y, b, h, true);// Skapar en ny triangel
        former.add(t);// Lägger till triangeln i listan
    }
    
    else if(this.RbtnRektangel.isSelected()){// Om radioknappen för rektangel är vald
        Form r = new Rektangel (x, y, b, h, true);// Skapar en ny rektangel
            former.add(r);// Lägger till rektangeln i listan
    }
    
    else if(this.RbtnCirkel.isSelected()){// Om radioknappen för cirkel är vald
        Form c = new Cirkel (x, y, h, true);// Skapar en ny cirkel
            former.add(c);// Lägger till cirkeln i listan
    }
    repaint();// Ritar om panelen så att den nya formen visas
    }//GEN-LAST:event_formMouseClicked

    private void jbtnHämtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHämtaActionPerformed
        former = fmgr.readFromFile(); // Läser in sparade former från fil
        
    repaint(); // Ritar om panelen med de inlästa formerna
    }//GEN-LAST:event_jbtnHämtaActionPerformed

    private void tJbtnStartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJbtnStartaActionPerformed
        if(this.tJbtnStarta.getText().equals("Start")){// Kontrollerar om knappen visar "Start"
           this.tJbtnStarta.setText("Stop");// Byter text till "Stop"
        start();// Startar animationen/tråden
       }
        else{
           this.tJbtnStarta.setText("Start");// Byter tillbaka texten till "Start"
           stop();// Stoppar animationen/tråden
       }
        // Uppdaterar alla former med aktuell running-status
        for (int i = 0; i < former.size(); i++) {
            
            former.get(i).setRunning(running);
        }
       repaint();// Ritar om panelen
    }//GEN-LAST:event_tJbtnStartaActionPerformed
    private void start() {// Startar tråden om ingen tråd redan körs
        if (trad == null) {// Kontrollerar att tråden inte redan finns
            trad = new Thread(this);// Skapar en ny tråd
            trad.start();// Startar tråden
            this.running = true;// Sätter running till true för att animationen ska köras
        }
    }

    private void stop() {// Stoppar tråden och animationen
        if (trad != null) {// Kontrollerar att det finns en aktiv tråd
            this.running = false;// Stoppar while-loopen i run-metoden
            trad = null;// Tar bort referensen till tråden
        }
    }

@Override
    public void run() {
        while (running) {// Körs så länge running är true
        
        // Flyttar alla former i X-led
        for (Form f : former) {
            f.moveX(2);
        }
        repaint();// Ritar om panelen efter förflyttning
        try {
            Thread.sleep(30);// Pausar tråden i 30 millisekunder
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();// Återställer interrupt-status
        break;// Avslutar loopen vid avbrott
        }
    }
}
@Override
    protected void paintComponent (Graphics g){
        super.paintComponent (g);// Anropar JPanel:s vanliga ritmetod
        
        // Ritar alla former i listan
        for (int i = 0; i<former.size(); i++){
            former.get(i).draw(g);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbtnCirkel;
    private javax.swing.JRadioButton RbtnRektangel;
    private javax.swing.JRadioButton RbtnTriangel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jbtnHämta;
    private javax.swing.JButton jbtnRensa;
    private javax.swing.JButton jbtnSpara;
    private javax.swing.JToggleButton tJbtnStarta;
    // End of variables declaration//GEN-END:variables
}

