/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package implementeringform;

import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author taglu01
 */
public class Form1JPanel extends javax.swing.JPanel {

    public ArrayList<Form> former = new ArrayList<>();
    FileManager fmgr = new FileManager();
    /**
     * Creates new form Form1JPanel
     */
    public Form1JPanel(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jbtnRensa = new javax.swing.JButton();
        jbtnSpara = new javax.swing.JButton();
        RbtnCirkel = new javax.swing.JRadioButton();
        RbtnTriangel = new javax.swing.JRadioButton();
        RbtnRektangel = new javax.swing.JRadioButton();
        jbtnHämta = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jbtnRensa.setText("Rensa");
        jbtnRensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRensaActionPerformed(evt);
            }
        });

        jbtnSpara.setText("Spara");
        jbtnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSparaActionPerformed(evt);
            }
        });

        buttonGroup1.add(RbtnCirkel);
        RbtnCirkel.setSelected(true);
        RbtnCirkel.setText("Cirkel");

        buttonGroup1.add(RbtnTriangel);
        RbtnTriangel.setText("Triangel");

        buttonGroup1.add(RbtnRektangel);
        RbtnRektangel.setText("Rektangel");

        jbtnHämta.setText("Hämta");
        jbtnHämta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHämtaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RbtnCirkel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbtnTriangel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbtnRektangel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jbtnSpara)
                        .addGap(3, 3, 3)
                        .addComponent(jbtnHämta))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnRensa)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSpara)
                    .addComponent(RbtnCirkel)
                    .addComponent(RbtnTriangel)
                    .addComponent(RbtnRektangel)
                    .addComponent(jbtnHämta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnRensa)
                .addContainerGap(232, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSparaActionPerformed
        fmgr.saveToFile(former);
    }//GEN-LAST:event_jbtnSparaActionPerformed

    private void jbtnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRensaActionPerformed
    this.former.clear();
    
    repaint();
    }//GEN-LAST:event_jbtnRensaActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    int x = evt.getX();
    int y = evt.getY();
    int b = (int) (Math.random() * 301) +5;
    int h = (int) (Math.random() * 50) +5;
    
    if(this.RbtnTriangel.isSelected()){
        Form t = new Triangel (x, y, b, h, true);
        former.add(t);
    }
    
    else if(this.RbtnRektangel.isSelected()){
        Form r = new Rektangel (x, y, b, h, true);
            former.add(r);
    }
    
    else if(this.RbtnCirkel.isSelected()){
        Form c = new Cirkel (x, y, h, true);
            former.add(c);
    }
    repaint();
    }//GEN-LAST:event_formMouseClicked

    private void jbtnHämtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHämtaActionPerformed
        former = fmgr.readFromFile();
        
    repaint();
    }//GEN-LAST:event_jbtnHämtaActionPerformed

@Override
    protected void paintComponent (Graphics g){
        super.paintComponent (g);
        for (int i = 0; i<former.size(); i++){
            former.get(i).draw(g);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbtnCirkel;
    private javax.swing.JRadioButton RbtnRektangel;
    private javax.swing.JRadioButton RbtnTriangel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jbtnHämta;
    private javax.swing.JButton jbtnRensa;
    private javax.swing.JButton jbtnSpara;
    // End of variables declaration//GEN-END:variables
}
